"""change pelanggaran to boolean

Revision ID: 3fa0cb0570d3
Revises: dd697cfc9870
Create Date: 2024-07-14 17:35:40.659681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa0cb0570d3'
down_revision = 'dd697cfc9870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_scan', schema=None) as batch_op:
        batch_op.alter_column('pelanggaran',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='pelanggaran::BOOLEAN')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_scan', schema=None) as batch_op:
        batch_op.alter_column('pelanggaran',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
