"""initial migrate

Revision ID: 52af35fc8b1e
Revises: 
Create Date: 2024-07-13 09:11:29.328920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52af35fc8b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('id_kelas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_kelas'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('pelanggaran', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_scan')
    op.drop_table('siswa')
    op.drop_table('kelas')
    # ### end Alembic commands ###
